// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_theme

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ThemeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"activate": schema.BoolAttribute{
				Optional: true,
			},
			"hash": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"source": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type ThemeModel struct {
	Activate types.Bool   `tfsdk:"activate"`
	Hash     types.String `tfsdk:"hash"`
	Name     types.String `tfsdk:"name"`
	Source   types.String `tfsdk:"source"`
}
