// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_site

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SiteDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"accent_color": schema.StringAttribute{
				Computed: true,
			},
			"allow_external_signup": schema.BoolAttribute{
				Computed: true,
			},
			"cover_image": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"icon": schema.StringAttribute{
				Computed: true,
			},
			"locale": schema.StringAttribute{
				Computed: true,
			},
			"logo": schema.StringAttribute{
				Computed: true,
			},
			"title": schema.StringAttribute{
				Computed: true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
			"version": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SiteModel struct {
	AccentColor         types.String `tfsdk:"accent_color"`
	AllowExternalSignup types.Bool   `tfsdk:"allow_external_signup"`
	CoverImage          types.String `tfsdk:"cover_image"`
	Description         types.String `tfsdk:"description"`
	Icon                types.String `tfsdk:"icon"`
	Locale              types.String `tfsdk:"locale"`
	Logo                types.String `tfsdk:"logo"`
	Title               types.String `tfsdk:"title"`
	Url                 types.String `tfsdk:"url"`
	Version             types.String `tfsdk:"version"`
}
