// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_ghost

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func GhostProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"address": schema.StringAttribute{
				Optional: true,
			},
			"admin_api_key": schema.StringAttribute{
				Optional: true,
			},
		},
	}
}

type GhostModel struct {
	Address     types.String `tfsdk:"address"`
	AdminApiKey types.String `tfsdk:"admin_api_key"`
}
